[package]
name = "inode_counter"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
itertools = "0.10.5"
ptree = "0.4.0"
rayon = "1.7.0"
structopt = "0.3.26"
walkdir = "2.3.3"